[project]
name = "pytorch-llmcompressor-notebook"
version = "0.1.0"
requires-python = "==3.12.*"

dependencies = [
    # PyTorch packages
    "tensorboard~=2.20.0",
    "torch==2.9.0",
    "torchvision==0.24.0",

    # llmcompressor packages
    "odh-notebooks-meta-llmcompressor-deps",
    "lm-eval~=0.4.9",

    # Datascience and useful extensions
    # TODO(RHAIENG-3041): Upgrade feast to ~=0.59.0 before RHOAI 3.4 GA
    "feast~=0.58.0",
    "odh-notebooks-meta-runtime-datascience-deps",

    # DB connectors
    "pymongo~=4.15.3",
    "psycopg~=3.3.2",
    "pyodbc~=5.3.0",
    "mysql-connector-python~=9.5.0",

    "odh-notebooks-meta-runtime-elyra-deps",

    # Base packages
    "setuptools~=80.9.0",
    "wheel==0.45.1",
]

[tool.uv.sources]
# https://github.com/astral-sh/uv/issues/13067#issuecomment-2824190008
odh-notebooks-meta-llmcompressor-deps = { path = "../../../dependencies/odh-notebooks-meta-llmcompressor-deps" }
odh-notebooks-meta-runtime-elyra-deps = { path = "../../../dependencies/odh-notebooks-meta-runtime-elyra-deps" }
odh-notebooks-meta-runtime-datascience-deps = { path = "../../../dependencies/odh-notebooks-meta-runtime-datascience-deps" }

[tool.uv]

environments = [
    "sys_platform == 'linux' and implementation_name == 'cpython'",
]
