# https://docs.astral.sh/uv/concepts/projects/config/
[project]
name = "pytorch-llmcompressor-notebook"
version = "0.1.0"
requires-python = "==3.12.*"

# https://docs.astral.sh/uv/concepts/projects/workspaces/#when-not-to-use-workspaces
dependencies = [
    # PyTorch packages
    "tensorboard~=2.20.0",
    "torch==2.9.0",
    "torchvision~=0.24.0",

    # llmcompressor packages
    # see https://redhat-internal.slack.com/archives/C0961HQ858Q/p1757007056725559?thread_ts=1756924127.136609&cid=C0961HQ858Q

    # llmcompressor packages
    "odh-notebooks-meta-llmcompressor-deps",
    "lm-eval~=0.4.9",

    # Datascience and useful extensions
    "feast~=0.59.0",
    "skl2onnx~=1.19.1",
    "odh-notebooks-meta-workbench-datascience-deps",

    # DB connectors
    "pymongo~=4.16.0",
    "psycopg~=3.3.2",
    "pyodbc~=5.3.0",
    "mysql-connector-python~=9.5.0",

    # JupyterLab packages
    "odh-elyra==4.3.2",
    "odh-jupyter-trash-cleanup==0.1.1",

    "jupyterlab==4.5.2",
    "jupyter-bokeh~=4.0.5",
    "jupyter-server~=2.17.0",
    "jupyter-server-proxy~=4.4.0",
    "jupyter-server-terminals~=0.5.3",
    "jupyterlab-git~=0.51.2",
    "jupyterlab-lsp~=5.1.0",
    "jupyterlab-widgets~=3.0.15",
    "jupyter-resource-usage~=1.1.1",
    "nbdime~=4.0.2",
    "nbgitpuller~=1.2.2",

    # Base packages
    "wheel~=0.46.3",
    "setuptools~=80.9.0",
]

## https://docs.astral.sh/uv/concepts/resolution/#dependency-metadata
#[[tool.uv.dependency-metadata]]
## TODO(HACK): vllm is a requirement, however, as compressed-tensors is pinned, this can't be installed together
#name = "vllm"
#version = "0.8.5"
#requires-dist = [
#    "compressed-tensors"
#]

# https://docs.astral.sh/uv/concepts/projects/dependencies/#dependency-sources
[tool.uv.sources]
# https://github.com/astral-sh/uv/issues/13067#issuecomment-2824190008
odh-notebooks-meta-llmcompressor-deps = { path = "../../../dependencies/odh-notebooks-meta-llmcompressor-deps" }
odh-notebooks-meta-workbench-datascience-deps = { path = "../../../dependencies/odh-notebooks-meta-workbench-datascience-deps" }

# https://docs.astral.sh/uv/concepts/resolution/#dependency-overrides
# https://docs.astral.sh/uv/reference/settings/#override-dependencies
[tool.uv]

environments = [
    "sys_platform == 'linux' and implementation_name == 'cpython'",
]
override-dependencies = [
    # RHAIENG-2458: CVE-2025-66418 urllib3 - override needed because odh-elyra pulls in
    # appengine-python-standard which has an obnoxious urllib3<2 constraint
    "urllib3>=2.6.0",
    # AIPCC-8698: python-lsp-server[all] has conflicting pyflakes/pycodestyle requirements
    # Using >= instead of ~= to allow broader compatibility during resolution
    # TODO: Remove this override before RHOAI 3.4 GA once AIPCC-8698 is resolved
    "python-lsp-server>=1.11.0",
]
