# https://docs.astral.sh/uv/concepts/projects/config/
[project]
name = "pytorch-llmcompressor-notebook"
version = "0.1.0"
requires-python = "==3.12.*"

# https://docs.astral.sh/uv/concepts/projects/workspaces/#when-not-to-use-workspaces
dependencies = [
    # see https://redhat-internal.slack.com/archives/C079FE5H94J/p1756933987117709?thread_ts=1756933154.294109&cid=C079FE5H94J
    # for a discussion on what version of torch to use

    # PyTorch packages
    "tensorboard~=2.20.0",
    "torch==2.7.1",
    "torchvision==0.22.1",

    # llmcompressor packages
    # see https://redhat-internal.slack.com/archives/C0961HQ858Q/p1757007056725559?thread_ts=1756924127.136609&cid=C0961HQ858Q
    "llmcompressor==0.7.1",
    "lm-eval~=0.4.8",

    # Datascience and useful extensions
    "boto3~=1.40.27",
    "kafka-python-ng~=2.2.3",
    "kfp~=2.14.3",
    "matplotlib~=3.10.1",
    "numpy~=2.2.6",
    "pandas~=2.2.3",
    "plotly~=6.0.0",
    "scikit-learn~=1.6.1",
    "scipy~=1.15.2",
    "skl2onnx~=1.18.0",
    "onnxconverter-common~=1.13.0", # Required for skl2onnx, as upgraded version is not compatible with protobuf
    "kubeflow-training==1.9.0",
    "feast~=0.53.0",

    # DB connectors
    "pymongo~=4.11.2",
    "psycopg~=3.2.5",
    "pyodbc~=5.2.0",
    "mysql-connector-python~=9.3.0",

    # JupyterLab packages
    "odh-elyra==4.2.4",
    "odh-jupyter-trash-cleanup==0.1.0",

    "jupyterlab==4.4.4",
    "jupyter-bokeh~=4.0.5",
    "jupyter-server~=2.16.0",
    "jupyter-server-proxy~=4.4.0",
    "jupyter-server-terminals~=0.5.3",
    "jupyterlab-git~=0.51.1",
    "jupyterlab-lsp~=5.1.0",
    "jupyterlab-widgets~=3.0.13",
    "jupyter-resource-usage~=1.1.1",
    "nbdime~=4.0.2",
    "nbgitpuller~=1.2.2",

    # Base packages
    "wheel~=0.45.1",
    "setuptools~=78.1.1",
]

## https://docs.astral.sh/uv/concepts/resolution/#dependency-metadata
#[[tool.uv.dependency-metadata]]
## TODO(HACK): vllm is a requirement, however, as compressed-tensors is pinned, this can't be installed together
#name = "vllm"
#version = "0.8.5"
#requires-dist = [
#    "compressed-tensors"
#]

# https://docs.astral.sh/uv/concepts/projects/dependencies/#dependency-sources
[tool.uv.sources]
# https://docs.astral.sh/uv/guides/integration/pytorch/#using-uv-with-pytorch
torch = [
      { index = "pytorch-cuda", marker = "platform_machine == 'x86_64'" },
      { index = "pytorch-cpu", marker = "platform_machine == 'aarch64'" }]
torchvision = [
            { index = "pytorch-cuda", marker = "platform_machine == 'x86_64'" },
            { index = "pytorch-cpu", marker = "platform_machine == 'aarch64'" }]

# https://docs.astral.sh/uv/concepts/indexes/#package-indexes
[[tool.uv.index]]
name = "pytorch-cuda"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

# Add CPU index for ARM64
[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

# https://docs.astral.sh/uv/concepts/resolution/#dependency-overrides
# https://docs.astral.sh/uv/reference/settings/#override-dependencies
[tool.uv]
# https://github.com/astral-sh/uv/issues/2686
# https://github.com/astral-sh/uv/issues/4422
override-dependencies = [
    # vllm is a requirement, however, as compressed-tensors is pinned, this can't be installed together
    "compressed-tensors",
]

# from https://redhat-internal.slack.com/archives/C079FE5H94J/p1756934476976759?thread_ts=1756933154.294109&cid=C079FE5H94J
constraint-dependencies = [
    "loguru==0.7.3",
    "pyyaml==6.0.2",
    "numpy==2.2.6",
    "requests==2.32.5",
    "tqdm==4.67.1",
    # apicc is still on torch 2.7.1
    # "torch==2.8.0",
    "transformers==4.55.2",
    "datasets==4.0.0",
    "accelerate==1.10.0",
    "pynvml==12.0.0",
    "pillow==10.4.0",
]

environments = [
    "sys_platform == 'linux' and implementation_name == 'cpython'",
]
