---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/opendatahub-io/notebooks/blob/main/jupyter/pytorch"
    opendatahub.io/notebook-image-name: "PyTorch"
    opendatahub.io/notebook-image-desc: "Jupyter notebook image with PyTorch libraries and dependencies to start experimenting with advanced AI/ML notebooks."
    opendatahub.io/notebook-image-order: "4"
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
  name: jupyter-pytorch-notebook
spec:
  lookupPolicy:
    local: true
  tags:
    # N Version of the image
    - annotations:
        # language=json
        opendatahub.io/notebook-software: |
          [
            {"name": "CUDA", "version": "12.6"},
            {"name": "Python", "version": "v3.11"},
            {"name": "PyTorch", "version": "2.6"}
          ]
        # language=json
        opendatahub.io/notebook-python-dependencies: |
          [
            {"name": "JupyterLab","version": "4.2"},
            {"name": "PyTorch", "version": "2.6"},
            {"name": "Tensorboard", "version": "2.19"},
            {"name": "Boto3", "version": "1.37"},
            {"name": "Kafka-Python-ng", "version": "2.2"},
            {"name": "Kfp", "version": "2.12"},
            {"name": "Matplotlib", "version": "3.10"},
            {"name": "Numpy", "version": "2.2"},
            {"name": "Pandas", "version": "2.2"},
            {"name": "Scikit-learn", "version": "1.6"},
            {"name": "Scipy", "version": "1.15"},
            {"name": "Odh-Elyra", "version": "4.2"},
            {"name": "PyMongo", "version": "4.11"},
            {"name": "Pyodbc", "version": "5.2"},
            {"name": "Codeflare-SDK", "version": "0.27"},
            {"name": "Sklearn-onnx", "version": "1.18"},
            {"name": "Psycopg", "version": "3.2"},
            {"name": "MySQL Connector/Python", "version": "9.2"},
            {"name": "Kubeflow-Training", "version": "1.9"}
          ]
        openshift.io/imported-from: quay.io/opendatahub/workbench-images
        opendatahub.io/workbench-image-recommended: 'true'
        opendatahub.io/notebook-build-commit: odh-workbench-jupyter-pytorch-cuda-py311-ubi9-commit-n_PLACEHOLDER
      from:
        kind: DockerImage
        name: odh-workbench-jupyter-pytorch-cuda-py311-ubi9-n_PLACEHOLDER
      name: "2025.1"
      referencePolicy:
        type: Source
    # N - 1 Version of the image
    - annotations:
        # language=json
        opendatahub.io/notebook-software: |
          [
            {"name": "CUDA", "version": "12.4"},
            {"name": "Python", "version": "v3.11"},
            {"name": "PyTorch", "version": "2.4"}
          ]
        # language=json
        opendatahub.io/notebook-python-dependencies: |
          [
            {"name": "JupyterLab","version": "4.2"},
            {"name": "PyTorch", "version": "2.4"},
            {"name": "Tensorboard", "version": "2.17"},
            {"name": "Boto3", "version": "1.35"},
            {"name": "Kafka-Python-ng", "version": "2.2"},
            {"name": "Kfp", "version": "2.9"},
            {"name": "Matplotlib", "version": "3.9"},
            {"name": "Numpy", "version": "2.1"},
            {"name": "Pandas", "version": "2.2"},
            {"name": "Scikit-learn", "version": "1.5"},
            {"name": "Scipy", "version": "1.14"},
            {"name": "Odh-Elyra", "version": "4.2"},
            {"name": "PyMongo", "version": "4.8"},
            {"name": "Pyodbc", "version": "5.1"},
            {"name": "Codeflare-SDK", "version": "0.26"},
            {"name": "Sklearn-onnx", "version": "1.17"},
            {"name": "Psycopg", "version": "3.2"},
            {"name": "MySQL Connector/Python", "version": "9.0"},
            {"name": "Kubeflow-Training", "version": "1.8"}
          ]
        openshift.io/imported-from: quay.io/opendatahub/workbench-images
        opendatahub.io/workbench-image-recommended: 'false'
        opendatahub.io/notebook-build-commit: odh-workbench-jupyter-pytorch-cuda-py311-ubi9-commit-n-1_PLACEHOLDER
      from:
        kind: DockerImage
        name: odh-workbench-jupyter-pytorch-cuda-py311-ubi9-n-1_PLACEHOLDER
      name: "2024.2"
      referencePolicy:
        type: Source
