---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/opendatahub-io/notebooks/tree/main/jupyter/minimal"
    opendatahub.io/notebook-image-name: "CUDA"
    opendatahub.io/notebook-image-desc: "Jupyter notebook image with GPU support and minimal dependency set to start experimenting with Jupyter environment."
    opendatahub.io/notebook-image-order: "3"
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
  name: jupyter-minimal-gpu-notebook
spec:
  lookupPolicy:
    local: true
  tags:
    # N Version of the image
    - annotations:
        opendatahub.io/notebook-software: '[{"name":"CUDA","version":"11.8"},{"name":"Python","version":"v3.9"}]'
        opendatahub.io/notebook-python-dependencies: '[{"name":"JupyterLab","version":"3.5"},{"name": "Notebook","version": "6.5"}]'
        openshift.io/imported-from: quay.io/opendatahub/workbench-images
        opendatahub.io/workbench-image-recommended: 'true'
        opendatahub.io/notebook-build-commit: "cf1b63e"
      from:
        kind: DockerImage
        name: $(odh-minimal-gpu-notebook-image-n)
      name: "2023.2"
      referencePolicy:
        type: Source
    # N-1 Version of the image
    - annotations:
        opendatahub.io/notebook-software: '[{"name":"CUDA","version":"11.8"},{"name":"Python","version":"v3.9"}]'
        opendatahub.io/notebook-python-dependencies: '[{"name":"JupyterLab","version":"3.5"},{"name":"Notebook","version":"6.5"}]'
        openshift.io/imported-from: quay.io/opendatahub/workbench-images
        opendatahub.io/workbench-image-recommended: 'false'
        opendatahub.io/notebook-build-commit: "17c2e49"
      from:
        kind: DockerImage
        name: $(odh-minimal-gpu-notebook-image-n-1)
      name: "2023.1"
      referencePolicy:
        type: Source
    # N-2 Version of the image
    - annotations:
        opendatahub.io/notebook-software: '[{"name":"CUDA","version":"11.4"},{"name":"Python","version":"v3.8"}]'
        opendatahub.io/notebook-python-dependencies: '[{"name":"JupyterLab","version":"3.2"},{"name":"Notebook","version":"6.4"}]'
        openshift.io/imported-from: quay.io/opendatahub/notebooks
        opendatahub.io/image-tag-outdated: 'true'
        opendatahub.io/notebook-build-commit: "4c8f26e"
      from:
        kind: DockerImage
        name: $(odh-minimal-gpu-notebook-image-n-2)
      name: "1.2"
      referencePolicy:
        type: Source
