---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/opendatahub-io/notebooks/tree/main/jupyter/datascience"
    opendatahub.io/notebook-image-name: "Jupyter | Data Science | CPU | Python 3.12"
    opendatahub.io/notebook-image-desc: "Jupyter notebook image with a set of data science libraries that advanced AI/ML notebooks will use as a base image to provide a standard for libraries available in all notebooks"
    opendatahub.io/notebook-image-order: "7"
  name: jupyter-datascience-notebook
spec:
  lookupPolicy:
    local: true
  tags:
    # N Version of the image
    - annotations:
        # language=json
        opendatahub.io/notebook-software: |
          [
            {"name": "Python", "version": "v3.12"}
          ]
        # language=json
        opendatahub.io/notebook-python-dependencies: |
          [
            {"name": "JupyterLab","version": "4.5"},
            {"name": "Boto3", "version": "1.42"},
            {"name": "Kafka-Python-ng", "version": "2.2"},
            {"name": "Kfp", "version": "2.15"},
            {"name": "Matplotlib", "version": "3.10"},
            {"name": "Numpy", "version": "2.4"},
            {"name": "Pandas", "version": "2.3"},
            {"name": "Scikit-learn", "version": "1.8"},
            {"name": "Scipy", "version": "1.16"},
            {"name": "Odh-Elyra", "version": "4.3"},
            {"name": "PyMongo", "version": "4.16"},
            {"name": "Pyodbc", "version": "5.3"},
            {"name": "Codeflare-SDK", "version": "0.34"},
            {"name": "Feast", "version": "0.59"},
            {"name": "Sklearn-onnx", "version": "1.19"},
            {"name": "Psycopg", "version": "3.3"},
            {"name": "MySQL Connector/Python", "version": "9.5"},
            {"name": "Kubeflow-Training", "version": "1.9"}
          ]
        openshift.io/imported-from: quay.io/opendatahub/workbench-images
        opendatahub.io/workbench-image-recommended: 'true'
        opendatahub.io/notebook-build-commit: odh-workbench-jupyter-datascience-cpu-py312-ubi9-commit-n_PLACEHOLDER
      from:
        kind: DockerImage
        name: odh-workbench-jupyter-datascience-cpu-py312-ubi9-n_PLACEHOLDER
      name: "3.4"
      referencePolicy:
        type: Source
    # N - 1 Version of the image
    - annotations:
        # language=json
        opendatahub.io/notebook-software: |
          [
            {"name": "Python", "version": "v3.12"}
          ]
        # language=json
        opendatahub.io/notebook-python-dependencies: |
          [
            {"name": "JupyterLab","version": "4.4"},
            {"name": "Boto3", "version": "1.40"},
            {"name": "Kafka-Python-ng", "version": "2.2"},
            {"name": "Kfp", "version": "2.14"},
            {"name": "Matplotlib", "version": "3.10"},
            {"name": "Numpy", "version": "2.3"},
            {"name": "Pandas", "version": "2.3"},
            {"name": "Scikit-learn", "version": "1.7"},
            {"name": "Scipy", "version": "1.16"},
            {"name": "Odh-Elyra", "version": "4.3"},
            {"name": "PyMongo", "version": "4.15"},
            {"name": "Pyodbc", "version": "5.2"},
            {"name": "Codeflare-SDK", "version": "0.33"},
            {"name": "Feast", "version": "0.59"},
            {"name": "Sklearn-onnx", "version": "1.19"},
            {"name": "Psycopg", "version": "3.2"},
            {"name": "MySQL Connector/Python", "version": "9.4"},
            {"name": "Kubeflow-Training", "version": "1.9"}
          ]
        openshift.io/imported-from: quay.io/opendatahub/workbench-images
        opendatahub.io/workbench-image-recommended: 'false'
        opendatahub.io/notebook-build-commit: odh-workbench-jupyter-datascience-cpu-py312-ubi9-commit-2025-2_PLACEHOLDER
      from:
        kind: DockerImage
        name: odh-workbench-jupyter-datascience-cpu-py312-ubi9-2025-2_PLACEHOLDER
      name: "2025.2"
      referencePolicy:
        type: Source
