---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com//opendatahub-io/notebooks/tree/main/jupyter/trustyai"
    opendatahub.io/notebook-image-name: "TrustyAI"
    opendatahub.io/notebook-image-desc: "Jupyter TrustyAI notebook integrates the TrustyAI Explainability Toolkit on Jupyter environment."
    opendatahub.io/notebook-image-order: "6"
  name: jupyter-trustyai-notebook
spec:
  lookupPolicy:
    local: true
  tags:
    # N Version of the image
    - annotations:
        # language=json
        opendatahub.io/notebook-software: |
          [
            {"name": "Python", "version": "v3.11"}
          ]
        # language=json
        opendatahub.io/notebook-python-dependencies: |
          [
            {"name": "TrustyAI", "version": "0.6"},
            {"name": "Transformers", "version": "4.36"},
            {"name": "Datasets", "version": "2.21"},
            {"name": "Accelerate", "version": "0.34"},
            {"name": "Torch", "version": "2.2"},
            {"name": "Boto3", "version": "1.35"},
            {"name": "Kafka-Python-ng", "version": "2.2"},
            {"name": "Kfp", "version": "2.9"},
            {"name": "Matplotlib", "version": "3.6"},
            {"name": "Numpy", "version": "1.24"},
            {"name": "Pandas", "version": "1.5"},
            {"name": "Scikit-learn", "version": "1.2"},
            {"name": "Scipy", "version": "1.14"},
            {"name": "Odh-Elyra", "version": "4.2"},
            {"name": "PyMongo", "version": "4.8"},
            {"name": "Pyodbc", "version": "5.1"},
            {"name": "Codeflare-SDK", "version": "0.23"},
            {"name": "Sklearn-onnx", "version": "1.17"},
            {"name": "Psycopg", "version": "3.2"},
            {"name": "MySQL Connector/Python", "version": "9.0"}
          ]
        openshift.io/imported-from: quay.io/opendatahub/workbench-images
        opendatahub.io/workbench-image-recommended: 'true'
        opendatahub.io/notebook-build-commit: $(odh-trustyai-notebook-image-commit-n)
      from:
        kind: DockerImage
        name: $(odh-trustyai-notebook-image-n)
      name: "2024.2"
      referencePolicy:
        type: Source
    # N-1 Version of the image
    - annotations:
        # language=json
        opendatahub.io/notebook-software: |
          [
            {"name": "Python", "version": "v3.9"}
          ]
        # language=json
        opendatahub.io/notebook-python-dependencies: |
          [
            {"name": "TrustyAI", "version": "0.6"},
            {"name": "Boto3", "version": "1.34"},
            {"name": "Kafka-Python", "version": "2.0"},
            {"name": "Kfp", "version": "2.8"},
            {"name": "Matplotlib", "version": "3.6"},
            {"name": "Numpy", "version": "1.24"},
            {"name": "Pandas", "version": "1.5"},
            {"name": "Scikit-learn", "version": "1.4"},
            {"name": "Scipy", "version": "1.12"},
            {"name": "Odh-Elyra", "version": "3.16"},
            {"name": "PyMongo", "version": "4.6"},
            {"name": "Pyodbc", "version": "5.1"},
            {"name": "Codeflare-SDK", "version": "0.21"},
            {"name": "Sklearn-onnx", "version": "1.16"},
            {"name": "Psycopg", "version": "3.1"},
            {"name": "MySQL Connector/Python", "version": "8.3"}
          ]
        openshift.io/imported-from: quay.io/opendatahub/workbench-images
        opendatahub.io/workbench-image-recommended: 'false'
        opendatahub.io/notebook-build-commit: $(odh-trustyai-notebook-image-commit-n-1)
      from:
        kind: DockerImage
        name: $(odh-trustyai-notebook-image-n-1)
      name: "2024.1"
      referencePolicy:
        type: Source
