---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/opendatahub-io/notebooks/blob/main/jupyter/rocm"
    opendatahub.io/notebook-image-name: "ROCm"
    opendatahub.io/notebook-image-desc: "Jupyter ROCm notebook image for ODH notebooks."
    opendatahub.io/notebook-image-order: "11"
    opendatahub.io/recommended-accelerators: '["amd.com/gpu"]'
  name: jupyter-rocm-minimal
spec:
  lookupPolicy:
    local: true
  tags:
    # N Version of the image
    - annotations:
        # language=json
        opendatahub.io/notebook-software: |
          [
            {"name": "ROCm", "version": "6.2"},
            {"name": "Python", "version": "v3.11"}
          ]
        # language=json
        opendatahub.io/notebook-python-dependencies: |
          [
            {"name": "JupyterLab", "version": "4.2"}
          ]
        openshift.io/imported-from: quay.io/opendatahub/workbench-images
        opendatahub.io/workbench-image-recommended: 'true'
        opendatahub.io/notebook-build-commit: $(odh-rocm-minimal-notebook-image-commit-n)
      from:
        kind: DockerImage
        name: $(odh-rocm-minimal-notebook-image-n)
      name: "2025.1"
      referencePolicy:
        type: Source
    # N - 1 Version of the image
    - annotations:
        # language=json
        opendatahub.io/notebook-software: |
          [
            {"name": "ROCm", "version": "6.1"},
            {"name": "Python", "version": "v3.11"}
          ]
        # language=json
        opendatahub.io/notebook-python-dependencies: |
          [
            {"name": "JupyterLab", "version": "4.2"}
          ]
        openshift.io/imported-from: quay.io/opendatahub/workbench-images
        opendatahub.io/workbench-image-recommended: 'false'
        opendatahub.io/notebook-build-commit: $(odh-rocm-minimal-notebook-image-commit-n-1)
      from:
        kind: DockerImage
        name: $(odh-rocm-minimal-notebook-image-n-1)
      name: "2024.2"
      referencePolicy:
        type: Source
