---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jupyter-minimal-notebook-imagestream.yaml
  - jupyter-datascience-notebook-imagestream.yaml
  - jupyter-minimal-gpu-notebook-imagestream.yaml
  - jupyter-pytorch-notebook-imagestream.yaml
  - jupyter-tensorflow-notebook-imagestream.yaml
  - jupyter-trustyai-notebook-imagestream.yaml
  - code-server-notebook-imagestream.yaml
  - rstudio-notebook-imagestream.yaml
  - rstudio-gpu-notebook-imagestream.yaml
  - jupyter-rocm-minimal-notebook-imagestream.yaml
  - jupyter-rocm-pytorch-notebook-imagestream.yaml
  - jupyter-rocm-tensorflow-notebook-imagestream.yaml
  - runtime-datascience-imagestream.yaml
  - runtime-minimal-imagestream.yaml
  - runtime-pytorch-imagestream.yaml
  - runtime-rocm-pytorch-imagestream.yaml
  - runtime-rocm-tensorflow-imagestream.yaml
  - runtime-tensorflow-imagestream.yaml

transformers:
  - labels.yaml

configMapGenerator:
  - name: notebooks-parameters
    env: params.env
  - name: notebook
    env: commit.env
generatorOptions:
  disableNameSuffixHash: true
vars:
  - name: odh-minimal-notebook-image-n
    objref:
      kind: ConfigMap
      name: notebooks-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-minimal-notebook-image-n
  - name: odh-minimal-notebook-image-n-1
    objref:
      kind: ConfigMap
      name: notebooks-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-minimal-notebook-image-n-1
  - name: odh-generic-data-science-notebook-image-n
    objref:
      kind: ConfigMap
      name: notebooks-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-generic-data-science-notebook-image-n
  - name: odh-generic-data-science-notebook-image-n-1
    objref:
      kind: ConfigMap
      name: notebooks-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-generic-data-science-notebook-image-n-1
  - name: odh-minimal-gpu-notebook-image-n
    objref:
      kind: ConfigMap
      name: notebooks-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-minimal-gpu-notebook-image-n
  - name: odh-minimal-gpu-notebook-image-n-1
    objref:
      kind: ConfigMap
      name: notebooks-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-minimal-gpu-notebook-image-n-1
  - name: odh-pytorch-gpu-notebook-image-n
    objref:
      kind: ConfigMap
      name: notebooks-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-pytorch-gpu-notebook-image-n
  - name: odh-pytorch-gpu-notebook-image-n-1
    objref:
      kind: ConfigMap
      name: notebooks-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-pytorch-gpu-notebook-image-n-1
  - name: odh-tensorflow-gpu-notebook-image-n
    objref:
      kind: ConfigMap
      name: notebooks-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-tensorflow-gpu-notebook-image-n
  - name: odh-tensorflow-gpu-notebook-image-n-1
    objref:
      kind: ConfigMap
      name: notebooks-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-tensorflow-gpu-notebook-image-n-1
  - name: odh-trustyai-notebook-image-n
    objref:
      kind: ConfigMap
      name: notebooks-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-trustyai-notebook-image-n
  - name: odh-trustyai-notebook-image-n-1
    objref:
      kind: ConfigMap
      name: notebooks-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-trustyai-notebook-image-n-1
  - name: odh-codeserver-notebook-image-n
    objref:
      kind: ConfigMap
      name: notebooks-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-codeserver-notebook-image-n
  - name: odh-codeserver-notebook-image-n-1
    objref:
      kind: ConfigMap
      name: notebooks-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-codeserver-notebook-image-n-1
  - name: odh-rstudio-notebook-image-n
    objref:
      kind: ConfigMap
      name: notebooks-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-rstudio-notebook-image-n
  - name: odh-rstudio-notebook-image-n-1
    objref:
      kind: ConfigMap
      name: notebooks-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-rstudio-notebook-image-n-1
  - name: odh-rstudio-gpu-notebook-image-n
    objref:
      kind: ConfigMap
      name: notebooks-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-rstudio-gpu-notebook-image-n
  - name: odh-rstudio-gpu-notebook-image-n-1
    objref:
      kind: ConfigMap
      name: notebooks-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-rstudio-gpu-notebook-image-n-1
  - name: odh-rocm-minimal-notebook-image-n
    objref:
      kind: ConfigMap
      name: notebooks-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-rocm-minimal-notebook-image-n
  - name: odh-rocm-minimal-notebook-image-n-1
    objref:
      kind: ConfigMap
      name: notebooks-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-rocm-minimal-notebook-image-n-1
  - name: odh-rocm-pytorch-notebook-image-n
    objref:
      kind: ConfigMap
      name: notebooks-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-rocm-pytorch-notebook-image-n
  - name: odh-rocm-pytorch-notebook-image-n-1
    objref:
      kind: ConfigMap
      name: notebooks-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-rocm-pytorch-notebook-image-n-1
  - name: odh-rocm-tensorflow-notebook-image-n
    objref:
      kind: ConfigMap
      name: notebooks-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-rocm-tensorflow-notebook-image-n
  - name: odh-rocm-tensorflow-notebook-image-n-1
    objref:
      kind: ConfigMap
      name: notebooks-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-rocm-tensorflow-notebook-image-n-1
  - name: odh-minimal-notebook-image-commit-n
    objref:
      kind: ConfigMap
      name: notebook
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-minimal-notebook-image-commit-n
  - name: odh-minimal-notebook-image-commit-n-1
    objref:
      kind: ConfigMap
      name: notebook
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-minimal-notebook-image-commit-n-1
  - name: odh-generic-data-science-notebook-image-commit-n
    objref:
      kind: ConfigMap
      name: notebook
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-generic-data-science-notebook-image-commit-n
  - name: odh-generic-data-science-notebook-image-commit-n-1
    objref:
      kind: ConfigMap
      name: notebook
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-generic-data-science-notebook-image-commit-n-1
  - name: odh-minimal-gpu-notebook-image-commit-n
    objref:
      kind: ConfigMap
      name: notebook
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-minimal-gpu-notebook-image-commit-n
  - name: odh-minimal-gpu-notebook-image-commit-n-1
    objref:
      kind: ConfigMap
      name: notebook
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-minimal-gpu-notebook-image-commit-n-1
  - name: odh-pytorch-gpu-notebook-image-commit-n
    objref:
      kind: ConfigMap
      name: notebook
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-pytorch-gpu-notebook-image-commit-n
  - name: odh-pytorch-gpu-notebook-image-commit-n-1
    objref:
      kind: ConfigMap
      name: notebook
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-pytorch-gpu-notebook-image-commit-n-1
  - name: odh-tensorflow-gpu-notebook-image-commit-n
    objref:
      kind: ConfigMap
      name: notebook
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-tensorflow-gpu-notebook-image-commit-n
  - name: odh-tensorflow-gpu-notebook-image-commit-n-1
    objref:
      kind: ConfigMap
      name: notebook
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-tensorflow-gpu-notebook-image-commit-n-1
  - name: odh-trustyai-notebook-image-commit-n
    objref:
      kind: ConfigMap
      name: notebook
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-trustyai-notebook-image-commit-n
  - name: odh-trustyai-notebook-image-commit-n-1
    objref:
      kind: ConfigMap
      name: notebook
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-trustyai-notebook-image-commit-n-1
  - name: odh-codeserver-notebook-image-commit-n
    objref:
      kind: ConfigMap
      name: notebook
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-codeserver-notebook-image-commit-n
  - name: odh-codeserver-notebook-image-commit-n-1
    objref:
      kind: ConfigMap
      name: notebook
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-codeserver-notebook-image-commit-n-1
  - name: odh-rstudio-notebook-image-commit-n
    objref:
      kind: ConfigMap
      name: notebook
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-rstudio-notebook-image-commit-n
  - name: odh-rstudio-notebook-image-commit-n-1
    objref:
      kind: ConfigMap
      name: notebook
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-rstudio-notebook-image-commit-n-1
  - name: odh-rstudio-gpu-notebook-image-commit-n
    objref:
      kind: ConfigMap
      name: notebook
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-rstudio-gpu-notebook-image-commit-n
  - name: odh-rstudio-gpu-notebook-image-commit-n-1
    objref:
      kind: ConfigMap
      name: notebook
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-rstudio-gpu-notebook-image-commit-n-1
  - name: odh-rocm-minimal-notebook-image-commit-n
    objref:
      kind: ConfigMap
      name: notebook
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-rocm-minimal-notebook-image-commit-n
  - name: odh-rocm-minimal-notebook-image-commit-n-1
    objref:
      kind: ConfigMap
      name: notebook
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-rocm-minimal-notebook-image-commit-n-1
  - name: odh-rocm-pytorch-notebook-image-commit-n
    objref:
      kind: ConfigMap
      name: notebook
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-rocm-pytorch-notebook-image-commit-n
  - name: odh-rocm-pytorch-notebook-image-commit-n-1
    objref:
      kind: ConfigMap
      name: notebook
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-rocm-pytorch-notebook-image-commit-n-1
  - name: odh-rocm-tensorflow-notebook-image-commit-n
    objref:
      kind: ConfigMap
      name: notebook
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-rocm-tensorflow-notebook-image-commit-n
  - name: odh-rocm-tensorflow-notebook-image-commit-n-1
    objref:
      kind: ConfigMap
      name: notebook
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-rocm-tensorflow-notebook-image-commit-n-1

configurations:
  - params.yaml
  - commit.yaml
