---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/opendatahub-io/notebooks/tree/main/rstudio"
    opendatahub.io/notebook-image-name: "CUDA - RStudio Server"
    opendatahub.io/notebook-image-desc: "RStudio Server Workbench image with an integrated development environment for R, a programming language designed for statistical computing and graphics."
    opendatahub.io/notebook-image-order: "10"
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
  name: rstudio-gpu-notebook
spec:
  lookupPolicy:
    local: true
  tags:
    # N Version of the image
    - annotations:
        # language=json
        opendatahub.io/notebook-software: |
          [
            {"name": "CUDA", "version": "12.6"},
            {"name": "R", "version": "v4.4"},
            {"name": "Python", "version": "v3.11"}
          ]
        # language=json
        opendatahub.io/notebook-python-dependencies: |
          [
            {"name": "rstudio-server", "version": "2024.12"}
          ]
        openshift.io/imported-from: quay.io/opendatahub/workbench-images
        opendatahub.io/workbench-image-recommended: 'true'
        opendatahub.io/notebook-build-commit: odh-rstudio-gpu-notebook-image-commit-n_PLACEHOLDER
      from:
        kind: DockerImage
        name: odh-rstudio-gpu-notebook-image-n_PLACEHOLDER
      name: "2025.1"
      referencePolicy:
        type: Source
    # N - 1 Version of the image
    - annotations:
        # language=json
        opendatahub.io/notebook-software: |
          [
            {"name": "CUDA", "version": "12.1"},
            {"name": "R", "version": "v4.4"},
            {"name": "Python", "version": "v3.11"}
          ]
        # language=json
        opendatahub.io/notebook-python-dependencies: |
          [
            {"name": "rstudio-server", "version": "2024.04"}
          ]
        openshift.io/imported-from: quay.io/opendatahub/workbench-images
        opendatahub.io/workbench-image-recommended: 'false'
        opendatahub.io/notebook-build-commit: odh-rstudio-gpu-notebook-image-commit-n-1_PLACEHOLDER
      from:
        kind: DockerImage
        name: odh-rstudio-gpu-notebook-image-n-1_PLACEHOLDER
      name: "2024.2"
      referencePolicy:
        type: Source
