---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-creator: RHOAI
    opendatahub.io/notebook-image-url: "https://github.com/red-hat-data-services/notebooks/tree/main/rstudio"
    opendatahub.io/notebook-image-name: "R Studio"
    opendatahub.io/notebook-image-desc: "R Studio Workbench image with an integrated development environment for R, a programming language designed for statistical computing and graphics."
  name: rstudio-rhel9
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      annotations:
        opendatahub.io/notebook-software: '[{"name":"R","version":"v4.3"},{"name":"Python","version":"v3.9"}]'
        opendatahub.io/notebook-python-dependencies: '[{"name":"r-studio","version":"4.3"}]'
      referencePolicy:
        type: Source
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: rstudio-rhel9
  labels:
    component: rstudio-rhel9-image
spec:
  source:
    type: Git
    git:
      uri: "https://github.com/red-hat-data-services/notebooks"
      ref: main
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: "DockerImage"
        name: "quay.io/modh/odh-base-rhel9:base-rhel9-python-3.9-20240131-378dafd"
      dockerfilePath: "rstudio/rhel9-python-3.9/Dockerfile"
      volumes:
        - name: secret-mvn
          source:
            type: Secret
            secret:
              secretName: rhel-subscription-secret
              defaultMode: 420
          mounts:
            - destinationPath: /opt/app-root/src/.sec
      noCache: true
  output:
    to:
      kind: ImageStreamTag
      name: "rstudio-rhel9:latest"
  runPolicy: Serial
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: "1"
      memory: 2Gi
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2
  triggers:
    - imageChange: {}
      type: ImageChange
