---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/runtime-image: "true"
  annotations:
    # TODO: once the restraction takes a final shape need to update that url
    opendatahub.io/runtime-image-url: "https://github.com//opendatahub-io/notebooks/tree/main/runtimes"
    opendatahub.io/runtime-image-name: "TensorFlow with ROCm and Python 3.11 (UBI9)"
    opendatahub.io/runtime-image-desc: "ROCm optimized TensorFlow runtime image for Elyra, enabling pipeline execution from Workbenches with TensorFlow libraries and dependencies, supporting different runtimes for various pipeline nodes."
  name: runtime-rocm-tensorflow
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations:
        # language=json
        opendatahub.io/runtime-image-metadata: |
          [
            {
              "display_name": "TensorFlow with ROCm and Python 3.11 (UBI9)",
              "metadata": {
                "tags": [
                  "rocm-tensorflow"
                ],
                "display_name": "TensorFlow with ROCm and Python 3.11 (UBI9)",
                "image_name": "quay.io/modh/workbench-images@sha256:7711bce783a52b259ba7e5f679d753c2f4e7868755350d612226f5c2ef267dbd",
                "pull_policy": "IfNotPresent"
              },
              "schema_name": "runtime-image"
            }
          ]
        openshift.io/imported-from: quay.io/modh/workbench-images
      from:
        kind: DockerImage
        name: quay.io/modh/workbench-images@sha256:7711bce783a52b259ba7e5f679d753c2f4e7868755350d612226f5c2ef267dbd
      name: "rocm-tensorflow"
      referencePolicy:
        type: Source
