---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/runtime-image: "true"
  annotations:
    opendatahub.io/runtime-image-url: "https://github.com//opendatahub-io/notebooks/tree/main/runtimes"
    opendatahub.io/runtime-image-name: "Python 3.11 (UBI9)"
    opendatahub.io/runtime-image-desc: "Minimal runtime image for Elyra, enabling pipeline execution from Workbenches with minimal dependency set to start experimenting with, for various pipeline nodes."
  name: runtime-minimal
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations:
        # language=json
        opendatahub.io/runtime-image-metadata: |
          [
            {
              "display_name": "Python 3.11 (UBI9)",
              "metadata": {
                "tags": [
                  "minimal"
                ],
                "display_name": "Python 3.11 (UBI9)",
                "pull_policy": "IfNotPresent"
              },
              "schema_name": "runtime-image"
            }
          ]
        openshift.io/imported-from: quay.io/modh/runtime-images
      from:
        kind: DockerImage
        name: quay.io/modh/runtime-images@sha256:c938190b9e562f995cced83465c3ab809099301107664170e9cddb1554c9912c
      name: "minimal"
      referencePolicy:
        type: Source
