# https://docs.travis-ci.com/user/billing-overview/#partner-queue-solution
os: linux
arch:
  - ppc64le
  - s390x

language: python
python:
  - "3.12"

install:
  - pip install uv
  - uv venv --python $(which python3.12)
  - uv sync --locked

script:
  - make test
