# ==============================================================================
# GitHub organization, repository, etc
# ==============================================================================

# 
settings.github.organization = "opendatahub-io"

# 
settings.github.repository = "notebooks"

# 
settings.github.stream = "upstream"


# ==============================================================================
# Quay repositories, tags, etc
# ==============================================================================

# 
settings.quay.organization = "opendatahub"
