[project]
name = "trustyai-notebook"
version = "0.1.0"
requires-python = "==3.12.*"

dependencies = [
    # PyTorch packages
    "torch==2.6.0+cu126",

    # torch deps that get missed by uv with universal resolution
    "nvidia-cuda-nvrtc-cu12==12.6.77 ; platform_machine == 'x86_64' and sys_platform == 'linux'",
    "nvidia-cuda-runtime-cu12==12.6.77 ; platform_machine == 'x86_64' and sys_platform == 'linux'",
    "nvidia-cuda-cupti-cu12==12.6.80 ; platform_machine == 'x86_64' and sys_platform == 'linux'",
    "nvidia-cudnn-cu12==9.5.1.17 ; platform_machine == 'x86_64' and sys_platform == 'linux'",
    "nvidia-cublas-cu12==12.6.4.1 ; platform_machine == 'x86_64' and sys_platform == 'linux'",
    "nvidia-cufft-cu12==11.3.0.4 ; platform_machine == 'x86_64' and sys_platform == 'linux'",
    "nvidia-curand-cu12==10.3.7.77 ; platform_machine == 'x86_64' and sys_platform == 'linux'",
    "nvidia-cusolver-cu12==11.7.1.2 ; platform_machine == 'x86_64' and sys_platform == 'linux'",
    "nvidia-cusparse-cu12==12.5.4.2 ; platform_machine == 'x86_64' and sys_platform == 'linux'",
    "nvidia-cusparselt-cu12==0.6.3 ; platform_machine == 'x86_64' and sys_platform == 'linux'",
    "nvidia-nccl-cu12==2.21.5 ; platform_machine == 'x86_64' and sys_platform == 'linux'",
    "nvidia-nvtx-cu12==12.6.77 ; platform_machine == 'x86_64' and sys_platform == 'linux'",
    "nvidia-nvjitlink-cu12==12.6.85 ; platform_machine == 'x86_64' and sys_platform == 'linux'",
    "triton==3.2.0 ; platform_machine == 'x86_64' and sys_platform == 'linux'",

    # TrustyAI packages
    # More information available at:
    #   - https://pypi.org/project/trustyai/
    #   - https://github.com/trustyai-explainability/trustyai-explainability-python/blob/main/requirements.txt
    "transformers~=4.55.0",
    "datasets~=3.4.1",
    "accelerate~=1.5.2",
    "trustyai~=0.6.2",
    # Datascience and useful extensions
    "boto3~=1.40.27",
    "kafka-python-ng~=2.2.3",
    "kfp~=2.14.3",
    "matplotlib~=3.10.3", # Should be pinned down to this version in order to be compatible with trustyai
    "numpy~=1.26.4", # Should be pinned down to this version in order to be compatible with trustyai
    "pandas~=1.5.3", # Should be pinned down to this version in order to be compatible with trustyai
    "plotly~=6.0.0",
    "scikit-learn~=1.7.0", # Should be pinned down to this version in order to be compatible with trustyai
    "scipy~=1.15.2",
    "skl2onnx~=1.18.0",
    "onnxconverter-common~=1.13.0", # Required for skl2onnx, as upgraded version is not compatible with protobuf
    "codeflare-sdk~=0.31.0",
    "kubeflow-training==1.9.2",

    # DB connectors
    "pymongo~=4.11.2",
    "psycopg~=3.2.5",
    "pyodbc~=5.2.0",
    "mysql-connector-python~=9.3.0",

    # JupyterLab packages
    "odh-elyra==4.2.4",
    "odh-jupyter-trash-cleanup==0.1.0",

    "jupyterlab==4.4.4",
    "jupyter-bokeh~=3.0.7", # trustyai 0.6.2 depends on jupyter-bokeh~=3.0.7
    "jupyter-server~=2.16.0",
    "jupyter-server-proxy~=4.4.0",
    "jupyter-server-terminals~=0.5.3",
    "jupyterlab-git~=0.51.1",
    "jupyterlab-lsp~=5.1.1",
    "jupyterlab-widgets~=3.0.15",
    "jupyter-resource-usage~=1.1.1",
    "nbdime~=4.0.2",
    "nbgitpuller~=1.2.2",

    # Base packages
    "wheel~=0.45.1",
    "setuptools~=78.1.1",
]

[tool.uv]
environments = [
    "sys_platform == 'linux' and implementation_name == 'cpython'",
]

[tool.uv.sources]
torch = { index = "pytorch-cuda" }

[[tool.uv.index]]
name = "pytorch-cuda"
url = "https://download.pytorch.org/whl/cu126"
explicit = true
