---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: runtime-
resources:
  - pod.yaml
images:
  - name: runtime-workbench
    newName: quay.io/opendatahub/workbench-images
    newTag: runtime-pytorch-ubi8-python-3.8
configMapGenerator:
  - name: req-config
    files:
      - requirements-elyra.txt
