# ==============================================================================
# Image - Basic metadata about the notebook image
# ==============================================================================

[image]

# ID of this image to be used internally
id = "jupyter-minimal-cpu-py312-ubi9"

# Name of this workbench image, including details like Python version, CPU or GPU versions, type of image, etc
name = "Jupyter | Minimal | CPU | Python 3.12"

# Reference URL for this workbench image
url = "https://github.com/opendatahub-io/notebooks/tree/main/jupyter/minimal"

# Notebook description that will appear in the catalog / dashboard UI
description = "Jupyter notebook image with minimal dependency set to start experimenting with Jupyter environment."


# ==============================================================================
# Dashboard - UI display configuration
# ==============================================================================

[dashboard]

# Order of this image in the selection box
workbench_order = 1

# Set this workbench as "Recommended" on the RHOAI / ODH dashboard UI
workbench_recommended = true

# Set as default workbench in the selection box
default_workbench = false


# ==============================================================================
# Build - platforms, arguments, additional settings
# ==============================================================================

[build]

# List of architectures that this image will be built into
platforms.cpu = ["x86_64", "s390x"]

# Directory to hold all generated Dockerfiles, pyproject.toml and etc
build.output_dir = "jupyter/minimal/ubi9-python-3.12/"

# If set to true, will generate the similar Dockerfile.konflux file
# If set to false, no Dockerfile.konflux file will be generated
build.generate_konflux_dockerfile = true
