[project]
name = "minimal-notebook"
version = "0.1.0"
requires-python = "==3.12.*"

dependencies = [
    # Subproject dependencies
    "notebooks-base-deps",
    "notebooks-jupyterlab-deps",
]

[tool.uv.sources]
notebooks-base-deps = { path = "../../../dependencies/base" }
notebooks-jupyterlab-deps = { path = "../../../dependencies/jupyterlab" }

[tool.uv]
environments = [
    "sys_platform == 'linux' and implementation_name == 'cpython'",
]
