[project]
name = "tensorflow-ubi9-python-3.12"
version = "0.1.0"
requires-python = "==3.12.*"

dependencies = [
    "tf2onnx~=1.16.1",

    # TensorFlow packages
    "tensorflow[and-cuda]~=2.20.0",
    "tensorboard~=2.20.0",

    # Datascience and useful extensions
    "boto3~=1.40.52",
    "kafka-python-ng~=2.2.3",
    "matplotlib~=3.10.7",
    "numpy~=2.1.3",
    "pandas~=2.3.3",
    "plotly~=6.3.1",
    "scikit-learn~=1.7.2",
    "scipy~=1.16.2",
    "skl2onnx~=1.19.1",
    # Required for skl2onnx, as upgraded version is not compatible with protobuf
    "onnxconverter-common~=1.13.0",
    "codeflare-sdk~=0.34.0",
    "feast~=0.59.0",

    # DB connectors
    "pymongo~=4.15.3",
    "psycopg~=3.2.10",
    "pyodbc~=5.2.0",
    "mysql-connector-python~=9.4.0",

    "odh-notebooks-meta-runtime-elyra-deps",

    # Base packages
    "setuptools~=80.9.0",
    "wheel~=0.45.1",
]

[tool.uv]

override-dependencies = [
    # tf2onnx has pinned protobuf version, that causes conflict with other packages
    "protobuf==6.31.1",
    "keras~=3.12.0"
]

environments = [
    "sys_platform == 'linux' and implementation_name == 'cpython'",
]

[tool.uv.sources]
odh-notebooks-meta-runtime-elyra-deps = { path = "../../../dependencies/odh-notebooks-meta-runtime-elyra-deps" }
