[project]
name = "tensorflow-ubi9-python-3.12"
version = "0.1.0"
requires-python = "==3.12.*"

dependencies = [

    # TensorFlow packages
    "tensorflow~=2.20.0",
    "tensorboard~=2.20.0",

    # Datascience and useful extensions
    "codeflare-sdk~=0.34.0",
    "feast~=0.59.0",
    "odh-notebooks-meta-runtime-datascience-deps",

    # DB connectors
    "pymongo~=4.16.0",
    "psycopg~=3.3.2",
    "pyodbc~=5.3.0",
    "mysql-connector-python~=9.5.0",

    "odh-notebooks-meta-runtime-elyra-deps",

    # Base packages
    "wheel~=0.46.3",
    "setuptools~=80.9.0",
]

[tool.uv]

environments = [
    "sys_platform == 'linux' and implementation_name == 'cpython'",
]

[tool.uv.sources]
odh-notebooks-meta-runtime-elyra-deps = { path = "../../../dependencies/odh-notebooks-meta-runtime-elyra-deps" }
odh-notebooks-meta-runtime-datascience-deps = { path = "../../../dependencies/odh-notebooks-meta-runtime-datascience-deps" }
