[project]
name = "tensorflow-ubi9-python-3.12"
version = "0.1.0"
requires-python = "==3.12.*"

dependencies = [
    "tf2onnx~=1.16.1",

    # TensorFlow packages
    "tensorflow[and-cuda]~=2.20.0",
    "tensorboard~=2.20.0",

    # Subproject dependencies
    "notebooks-base-deps",
    "notebooks-elyra-runtime-deps",
    "notebooks-datascience-deps",
    "notebooks-db-connectors-deps",
]

[tool.uv.sources]
notebooks-base-deps = { path = "../../../dependencies/base" }
notebooks-elyra-runtime-deps = { path = "../../../dependencies/elyra-runtime" }
notebooks-datascience-deps = { path = "../../../dependencies/datascience" }
notebooks-db-connectors-deps = { path = "../../../dependencies/db-connectors" }

[tool.uv]

override-dependencies = [
    # tf2onnx has pinned protobuf version, that causes conflict with other packages
    "protobuf==6.31.1",
    "keras~=3.13.2"
]

environments = [
    "sys_platform == 'linux' and implementation_name == 'cpython'",
]
