[project]
name = "rocm-tensorflow-ubi9-python-3.12"
version = "0.1.0"
requires-python = "==3.12.*"

dependencies = [
    "tf2onnx~=1.16.1",

    # ROCm TensorFlow packages
    # https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/3rd-party/tensorflow-install.html#using-a-wheels-package
    # TODO(jdanek): consider adding #sha256=814a5e4842b0c92d63c7a0bb4df0baf51ff2db8615535d83fe8958204b840598
    "tensorflow-rocm @ https://repo.radeon.com/rocm/manylinux/rocm-rel-6.4/tensorflow_rocm-2.18.1-cp312-cp312-manylinux_2_28_x86_64.whl",
    # tensorflow-rocm==2.x needs tensorboard>=2.x,<2.x+1
    "tensorboard~=2.18.0",

    # Datascience and useful extensions
    # TODO(RHAIENG-3039): Re-enable codeflare-sdk before RHOAI 3.4 GA
    "codeflare-sdk~=0.34.0",
    "odh-notebooks-meta-runtime-datascience-deps",

    # DB connectors
    "pymongo~=4.15.3",
    "psycopg~=3.3.2",
    "pyodbc~=5.3.0",
    "mysql-connector-python~=9.5.0",

    "odh-notebooks-meta-runtime-elyra-deps",

    # Base packages
    "setuptools==80.9.0",
    "wheel==0.45.1",
]

[tool.uv]

override-dependencies = [
    # tf2onnx has pinned protobuf version, that causes conflict with other packages
    "protobuf==6.31.1",
    "keras~=3.12.0"
]

constraint-dependencies = [
    # AttributeError: module 'ml_dtypes' has no attribute 'float4_e2m1fn'
    "onnx<1.19.0",
]

environments = [
    "sys_platform == 'linux' and implementation_name == 'cpython'",
]

[tool.uv.sources]
odh-notebooks-meta-runtime-elyra-deps = { path = "../../../dependencies/odh-notebooks-meta-runtime-elyra-deps" }
odh-notebooks-meta-runtime-datascience-deps = { path = "../../../dependencies/odh-notebooks-meta-runtime-datascience-deps" }