[project]
name = "rocm-tensorflow-ubi9-python-3.12"
version = "0.1.0"
requires-python = "==3.12.*"

dependencies = [
    "tf2onnx~=1.16.1",

    # ROCm TensorFlow packages
    # https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/3rd-party/tensorflow-install.html#using-a-wheels-package
    # TODO(jdanek): consider adding #sha256=814a5e4842b0c92d63c7a0bb4df0baf51ff2db8615535d83fe8958204b840598
    "tensorflow-rocm @ https://repo.radeon.com/rocm/manylinux/rocm-rel-6.3/tensorflow_rocm-2.17.0-cp312-cp312-manylinux_2_28_x86_64.whl",
    # tensorflow-rocm==2.x needs tensorboard>=2.x,<2.x+1
    "tensorboard~=2.17.0",

    # Datascience and useful extensions
    "boto3~=1.40.52",
    "kafka-python-ng~=2.2.3",
    "matplotlib~=3.10.7",
    "numpy~=1.26.4",
    "pandas~=2.3.3",
    "plotly~=6.3.1",
    "scikit-learn~=1.7.2",
    "scipy~=1.16.2",
    "skl2onnx~=1.19.1",
    # Required for skl2onnx, as upgraded version is not compatible with protobuf
    "onnxconverter-common~=1.13.0",
    "codeflare-sdk~=0.33.0",

    # DB connectors
    "pymongo~=4.15.3",
    "psycopg~=3.2.10",
    "pyodbc~=5.2.0",
    "mysql-connector-python~=9.4.0",

    # This is a comprehensive list of python dependencies that Elyra requires to execute Jupyter notebooks.
    "ipykernel~=6.30.1",
    "ipython~=9.6.0",
    "ipython-genutils~=0.2.0",
    "jinja2>=3.1.6",
    "jupyter-client~=8.6.3",
    "jupyter-core~=5.8.1",
    "markupsafe~=3.0.3",
    "minio~=7.2.18",
    "nbclient~=0.10.2",
    "nbconvert~=7.16.6",
    "nbformat~=5.10.4",
    "papermill~=2.6.0",
    "pyzmq~=27.1.0",
    "prompt-toolkit~=3.0.52",
    "requests~=2.32.5",
    "tornado~=6.5.2",
    "traitlets~=5.14.3",
    "urllib3~=2.5.0",

    # Base packages
    "setuptools==80.9.0",
    "wheel==0.45.1",
]

[tool.uv]

override-dependencies = [
    # tf2onnx has pinned protobuf version, that causes conflict with other packages
    "protobuf==6.31.1",
    "keras~=3.12.0"
]

constraint-dependencies = [
    # AttributeError: module 'ml_dtypes' has no attribute 'float4_e2m1fn'
    "onnx<1.19.0",
]

environments = [
    "sys_platform == 'linux' and implementation_name == 'cpython'",
]
