[project]
name = "rstudio-notebook"
version = "0.1.0"
requires-python = "==3.12.*"

dependencies = [
    # Base packages
    "wheel~=0.46.3",
    "setuptools~=80.9.0",
]

[tool.uv]
environments = [
    "sys_platform == 'linux' and implementation_name == 'cpython'",
]
