---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: rstudio-
resources:
  - pod.yaml
transformers:
  - labels.yaml
images:
  - name: rstudio-workbench
    newName: quay.io/opendatahub/workbench-images
    newTag: rstudio-c9s-python-3.11
