[project]
name = "notebooks"
version = "0.1.0"
requires-python = "==3.12.*"

dependencies = [
    # Subproject dependencies
    "notebooks-base-deps",
    "notebooks-datascience-deps",
    
    # Additional useful packages
    "opencensus~=0.11.4",
    "smart-open~=7.5.0",
    "virtualenv~=20.36.1",
    # https://issues.redhat.com/browse/AIPCC-9544 py-spy excluded on ppc64le for codeserver
    "py-spy~=0.4.1; platform_machine != 's390x' and platform_machine != 'ppc64le'",
    "prometheus-client~=0.24.1",
]

[tool.uv.sources]
notebooks-base-deps = { path = "../../dependencies/base" }
notebooks-datascience-deps = { path = "../../dependencies/datascience" }

[tool.uv]
environments = [
    "sys_platform == 'linux' and implementation_name == 'cpython'",
]
override-dependencies = [
    # RHAIENG-2458: CVE-2025-66418 urllib3 decompression vulnerability
    # Upstream: https://github.com/kubernetes-client/python/issues/2458
    "urllib3>=2.6.0",
]
