---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/opendatahub-io/notebooks/blob/main/jupyter/tensorflow"
    opendatahub.io/notebook-image-name: "Jupyter | TensorFlow | CUDA | Python 3.12"
    opendatahub.io/notebook-image-desc: "Jupyter notebook image with TensorFlow libraries and dependencies to start experimenting with advanced AI/ML notebooks."
    opendatahub.io/notebook-image-order: "14"
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
  name: jupyter-tensorflow-cuda-py312-ubi9
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations:
        # language=json
        opendatahub.io/notebook-software: |
          [
            {"name": "CUDA", "version": "12.6"},
            {"name": "Python", "version": "v3.12"},
            {"name": "TensorFlow", "version": "2.19"}
          ]
        # language=json
        opendatahub.io/notebook-python-dependencies: |
          [
            {"name": "JupyterLab","version": "4.4"},
            {"name": "TensorFlow", "version": "2.19"},
            {"name": "Tensorboard", "version": "2.19"},
            {"name": "Nvidia-CUDA-CU12-Bundle", "version": "12.5"},
            {"name": "Boto3", "version": "1.37"},
            {"name": "Kafka-Python-ng", "version": "2.2"},
            {"name": "Kfp", "version": "2.12"},
            {"name": "Matplotlib", "version": "3.10"},
            {"name": "Numpy", "version": "1.26"},
            {"name": "Pandas", "version": "2.2"},
            {"name": "Scikit-learn", "version": "1.6"},
            {"name": "Scipy", "version": "1.15"},
            {"name": "Odh-Elyra", "version": "4.2"},
            {"name": "PyMongo", "version": "4.11"},
            {"name": "Pyodbc", "version": "5.2"},
            {"name": "Codeflare-SDK", "version": "0.29"},
            {"name": "Sklearn-onnx", "version": "1.18"},
            {"name": "Psycopg", "version": "3.2"},
            {"name": "MySQL Connector/Python", "version": "9.3"}
          ]
        openshift.io/imported-from: quay.io/opendatahub/workbench-images
        opendatahub.io/workbench-image-recommended: 'true'
        opendatahub.io/notebook-build-commit: odh-workbench-jupyter-tensorflow-cuda-py312-ubi9-commit-n_PLACEHOLDER
      from:
        kind: DockerImage
        name: odh-workbench-jupyter-tensorflow-cuda-py312-ubi9-n_PLACEHOLDER
      name: "2025.1"
      referencePolicy:
        type: Source
