---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/opendatahub-io/notebooks/tree/main/jupyter/datascience"
    opendatahub.io/notebook-image-name: "Jupyter | Data Science | CPU | Python 3.12"
    opendatahub.io/notebook-image-desc: "Jupyter notebook image with a set of data science libraries that advanced AI/ML notebooks will use as a base image to provide a standard for libraries avialable in all notebooks"
    opendatahub.io/notebook-image-order: "8"
  name: jupyter-datascience-cpu-py312-ubi9
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations:
        # language=json
        opendatahub.io/notebook-software: |
          [
            {"name": "Python", "version": "v3.12"}
          ]
        # language=json
        opendatahub.io/notebook-python-dependencies: |
          [
            {"name": "JupyterLab","version": "4.4"},
            {"name": "Boto3", "version": "1.37"},
            {"name": "Kafka-Python-ng", "version": "2.2"},
            {"name": "Kfp", "version": "2.12"},
            {"name": "Matplotlib", "version": "3.10"},
            {"name": "Numpy", "version": "2.2"},
            {"name": "Pandas", "version": "2.2"},
            {"name": "Scikit-learn", "version": "1.6"},
            {"name": "Scipy", "version": "1.15"},
            {"name": "Odh-Elyra", "version": "4.2"},
            {"name": "PyMongo", "version": "4.11"},
            {"name": "Pyodbc", "version": "5.2"},
            {"name": "Codeflare-SDK", "version": "0.30"},
            {"name": "Sklearn-onnx", "version": "1.18"},
            {"name": "Psycopg", "version": "3.2"},
            {"name": "MySQL Connector/Python", "version": "9.3"},
            {"name": "Kubeflow-Training", "version": "1.9"}
          ]
        openshift.io/imported-from: quay.io/opendatahub/workbench-images
        opendatahub.io/workbench-image-recommended: 'true'
        opendatahub.io/notebook-build-commit: odh-workbench-jupyter-datascience-cpu-py312-ubi9-commit-n_PLACEHOLDER
      from:
        kind: DockerImage
        name: odh-workbench-jupyter-datascience-cpu-py312-ubi9-n_PLACEHOLDER
      name: "2025.1"
      referencePolicy:
        type: Source
