---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: jupyter-pytorch-ubi9-python-3-11-
resources:
  - service.yaml
  - statefulset.yaml
images:
  - name: quay.io/opendatahub/workbench-images
    newName: quay.io/opendatahub/workbench-images
    newTag: jupyter-pytorch-ubi9-python-3.11
labels:
  - includeSelectors: true
    pairs:
      app: jupyter-pytorch-ubi9-python-3-11
