---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: jupyter-datascience-ubi8-python-3-8-
commonLabels:
  app: jupyter-datascience-ubi8-python-3-8
resources:
  - service.yaml
  - statefulset.yaml
images:
  - name: quay.io/opendatahub/notebooks
    newName: quay.io/opendatahub/notebooks
    newTag: jupyter-datascience-ubi8-python-3.8
