name: Insta Merge Konflux PRs

on:
  pull_request:
    paths:
      - manifests/base/params-latest.env
    types:
      - opened
    branches:
      - 'main'

permissions:
  contents: write
  pull-requests: write
  checks: write
  security-events: write
  statuses: write

jobs:
  instant-merge:
    runs-on: ubuntu-latest
    steps:
      - name: insta-merge
        if: ${{ github.event.sender.login == 'red-hat-konflux[bot]' && ( contains(github.event.pull_request.title, 'Update odh-workbench-jupyter-') || contains(github.event.pull_request.title, 'Update odh-workbench-codeserver-') || contains(github.event.pull_request.title, 'Update odh-pipeline-runtime-') ) }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh pr merge --merge --admin ${{ github.event.pull_request.html_url }}