---
# The aim of this GitHub workflow is to update the runtimes ImageStreams
name: Update Runtime ImageStreams SHA digests
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      user-hash:
        required: false
        description: "Optional: Specify a Git hash (it should exists on the main branch history)"

env:
  USER_HASH: ${{ github.event.inputs.user-hash }}
  REPO_ORG: ${{ github.repository_owner }}
  TMP_BRANCH: tmp-runtimes-sync-${{ github.run_id }}
  BRANCH_NAME: 'main'

jobs:
  update-runtimes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Install Skopeo CLI
        shell: bash
        run: |
          sudo apt-get -y update
          sudo apt-get -y install skopeo

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: Create a new branch
        run: |
         echo ${{ env.TMP_BRANCH }}
         git checkout -b ${{ env.TMP_BRANCH }}
         git push --set-upstream origin ${{ env.TMP_BRANCH }}

      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.TMP_BRANCH }}
          fetch-depth: 0

      - name: Invoke script to handle the update
        shell: bash
        run: |
          bash ${GITHUB_WORKSPACE}/ci/runtimes-digest-updater.sh "${{ env.USER_HASH }}" "${{ env.REPO_ORG }}"

      - name: Commit the changes
        run: |
          if [[ $(git status --porcelain | wc -l) -gt 0 ]]; then
              git fetch origin "${{ env.TMP_BRANCH }}" && \
              git pull origin "${{ env.TMP_BRANCH }}" && \
              git add "manifests/base/runtime-*" && \
              git commit -m "Update file via ${{ env.TMP_BRANCH }} GitHub action" && \
              git push origin "${{ env.TMP_BRANCH }}"
          else
              echo "There were no changes detected in the images for the ${{ env.BRANCH_NAME }}"
          fi

      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ env.TMP_BRANCH }}
          destination_branch: ${{ env.BRANCH_NAME }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "automated pr"
          pr_title: "[Runtimes Updater Action] Update Runtimes ImageStream files"
          pr_body: |
            :rocket: This is an automated Pull Request.
            Created by `/.github/workflows/runtimes-digest-updater-upstream.yaml`

            :exclamation: **IMPORTANT NOTE**: Remember to delete the ` ${{ env.TMP_BRANCH }}` branch after merging the changes
